# Generated by Django 4.2.5 on 2024-04-30 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0018_alter_stop_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stop',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
